"""Replace availability grid with overlap-based scheduling (15-min slots)

Revision ID: 6b5093fffa7e
Revises: bd58488d6f14
Create Date: 2026-07-12 21:14:11.136683

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6b5093fffa7e'
down_revision = 'bd58488d6f14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('availability')
    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reservation_period', postgresql.TSRANGE(), sa.Computed("tsrange(time_slot, time_slot + interval '2 hours')", persisted=True), nullable=True))

    # ### end Alembic commands ###

    # Manually added: btree_gist lets a GiST exclusion constraint mix an equality
    # check (table_number) with a range-overlap check (reservation_period), which
    # is how Postgres enforces "no two overlapping reservations for the same table"
    # atomically, with no application-level locking required.
    op.execute("CREATE EXTENSION IF NOT EXISTS btree_gist")
    op.execute(
        "ALTER TABLE reservations "
        "ADD CONSTRAINT no_overlapping_reservations "
        "EXCLUDE USING gist (table_number WITH =, reservation_period WITH &&)"
    )


def downgrade():
    # Manually added: drop the exclusion constraint before the column it depends on.
    op.execute("ALTER TABLE reservations DROP CONSTRAINT no_overlapping_reservations")

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.drop_column('reservation_period')

    op.create_table('availability',
    sa.Column('availability_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('table_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('timeslot', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('reservation_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('reserved', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservations.reservation_id'], name=op.f('availability_reservation_id_fkey')),
    sa.ForeignKeyConstraint(['table_number'], ['tables.table_number'], name=op.f('availability_table_number_fkey')),
    sa.PrimaryKeyConstraint('availability_id', name=op.f('availability_pkey')),
    sa.UniqueConstraint('table_number', 'timeslot', name=op.f('uq_table_timeslot'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
