"""Create customers, tables, reservations, availability tables

Revision ID: bd58488d6f14
Revises: 
Create Date: 2026-07-10 22:26:06.656117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd58488d6f14'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('customer_name', sa.String(length=80), nullable=False),
    sa.Column('customer_email', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('newsletter_signup', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('customer_id')
    )
    op.create_table('tables',
    sa.Column('table_number', sa.Integer(), nullable=False),
    sa.Column('seat_capacity', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('table_number')
    )
    op.create_table('reservations',
    sa.Column('reservation_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('time_slot', sa.DateTime(), nullable=False),
    sa.Column('table_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], ),
    sa.ForeignKeyConstraint(['table_number'], ['tables.table_number'], ),
    sa.PrimaryKeyConstraint('reservation_id')
    )
    op.create_table('availability',
    sa.Column('availability_id', sa.Integer(), nullable=False),
    sa.Column('table_number', sa.Integer(), nullable=False),
    sa.Column('timeslot', sa.DateTime(), nullable=False),
    sa.Column('reservation_id', sa.Integer(), nullable=True),
    sa.Column('reserved', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservations.reservation_id'], ),
    sa.ForeignKeyConstraint(['table_number'], ['tables.table_number'], ),
    sa.PrimaryKeyConstraint('availability_id'),
    sa.UniqueConstraint('table_number', 'timeslot', name='uq_table_timeslot')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('availability')
    op.drop_table('reservations')
    op.drop_table('tables')
    op.drop_table('customers')
    # ### end Alembic commands ###
